---
title: "QCM Statistique descriptive"
author: "Ali Hajj Hassan, Hazem HASAN"
date: "7 octobre 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Vrai ou Faux
#### Les lignes de commande suivantes affichent le vecteur ligne
#### [1] 1 2 3 4 5 : vrai ou faux et pourquoi ?
1. [ ] `(1,2,3,4,5)`
```{r}
#(1,2,3,4,5)
# il manque le c, Erreur : ',' inattendu(e) in "(1,"
```

2. [ ] `c(1,2,3,4,5)`
```{r}
c(1,2,3,4,5)
```

3. [ ] `1:5`
```{r}
1:5
```
4. [ ] `1,5)`
```{r}
#1,5)
# Error il manque le c( et en plus c(1:5)
```
5. [ ] `rep(1,5)`
```{r}
rep(1,5)
```
6. [ ] `seq(1,5)`
```{r}
seq(1,5)
```
7. [ ] `cumsum(rep(1,5))`
```{r}
cumsum(rep(1,5))
```
8. [ ] `sort(seq(5,1,-1))`
```{r}
sort(seq(5,1,-1))
```
9. [ ] `for (i in 1:5){v[i] <- i}`
```{r}
# for (i in 1:5){v[i] <- i}
# l'objet v n'existe pas
```
10. [ ] `v <- rep(1,5); for (i in 1:5){v[i] <- i}; v`
```{r}
v <- rep(1,5); for (i in 1:5){v[i] <- i}; v
```
11. [ ] `v <- 1; for (i in 2:5){append(v,i)}; v`
```{r message=TRUE, warning=TRUE}
v <- 1; for (i in 2:5){append(v,i)}; v
```
12. [ ] `v <- 1; for (i in 2:5){v <- append(v,i)}; v`
```{r message=FALSE}
v <- 1; for (i in 2:5){v <- append(v,i)}; v
```
13. [ ] `v <- 1; for (i in 2:5){v <- c(v,i)}; v`
```{r}
v <- 1; for (i in 2:5){v <- c(v,i)}; v
```
14. [ ] `v <- 1; for (i in 2:5){v <- rbind(v,i)}; v`
```{r}
v <- 1; for (i in 2:5){v <- rbind(v,i)}; v
```
15. [ ] `v <- rep(1,5); while (i<5){v[i] <- i}; v`
```{r}
v <- rep(1,5); while (i<5){v[i] <- i}; v
```
16. [ ] `v<- 1; i<-1; while (i<5){i<-i+1; v[i] <- i}; v`
```{r}
v<- 1; i<-1; while (i<5){i<-i+1; v[i] <- i}; v
```

